### ISSUE TITLE
NuGet package update

### ISSUE THREAD

**Issue by MitchGH** [ALabrada/Neuronic.Filters#2]
Hello,
I need to design a LowPassChebyshev filter and have seen the actual NuGet version do not contain your code updates here on Git.
Would it be possible to update the NuGet package to the actual Git version?

**Comment by ALabrada** [comment]
Hello,
I just uploaded the package, so it should be available soon.

**Comment by MitchGH** [comment]
The updated version is available now.
Thank you very much for your work.
